name: Deploy Lambda Function

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .

    - name: Package Lambda function
      run: |
        zip -r function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: eu-west-1

    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code --function-name bot --zip-file fileb://function.zip

    - name: Update Lambda environment variables
      run: |
        # Retry mechanism with exponential backoff
        MAX_RETRIES=5
        RETRY_DELAY=5
        for ((i=1; i<=MAX_RETRIES; i++)); do
          echo "Attempt $i to update Lambda configuration..."
          aws lambda update-function-configuration --function-name bot --environment "Variables={USERNAMES='${{ secrets.USERNAMES }}',TELEGRAM_BOT_TOKEN='${{ secrets.TELEGRAM_BOT_TOKEN }}',AOC_TOKEN='${{ secrets.AOC_TOKEN }}',AOC_LEADERBOARD='${{ secrets.AOC_LEADERBOARD }}',AOC_USER_IDS='${{ secrets.AOC_USER_IDS }}'}" && break # Exit loop if successful

          if [[ $i -lt MAX_RETRIES ]]; then
            echo "Update failed. Retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
            RETRY_DELAY=$((RETRY_DELAY * 2)) # Exponential backoff
          else
            echo "Max retries reached. Exiting."
            exit 1
          fi
        done
